{{- if .Values.backendConfig.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.backendConfig.name | default "payment-backend-config" }}
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.backendConfig.cloudArmorPolicy }}
  securityPolicy:
    name: {{ .Values.backendConfig.cloudArmorPolicy }}
  {{- end }}
  timeoutSec: {{ .Values.backendConfig.timeoutSec | default 30 }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.backendConfig.connectionDraining.drainingTimeoutSec | default 60 }}
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: {{ .Values.backendConfig.healthCheck.requestPath | default "/actuator/health/liveness" }}
    port: {{ .Values.backendConfig.healthCheck.port | default 8080 }}
{{- end }}
