{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "payment-app.fullname" . }}-netpol
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "payment-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow incoming traffic from Ingress controller and Prometheus monitoring
    - from:
        {{- range .Values.networkPolicy.allowIngressFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
        - podSelector: {} # Allow pods in the same namespace
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow intra-namespace Kafka communication
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 9092
    # Allow outbound PostgreSQL communication (Cloud SQL private IP)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
